[theme]
primaryColor = "#0058cc"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b4d"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"   # Доступ с других компьютеров по IP (локальная сеть)
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
